server:
  port: ${PORT:8098}

# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

# custom attribute for the actuator info endpoint
info:
  app:
    name: bookstore-service

# give the application a name
spring:
  application:
    name: bookstore-service

# custom logging settings
logging:
  level:
  - ".=info"
  - "vn.its=debug"
  - "org.springframework=info"